// ============================================================
// NARAYANA HEALTH — MOCK DATA
// Based on public narayanahealth.org content
// 30+ specialities, 24+ hospitals, sample doctors
// ============================================================

export const specialities = [
  { id: 'cardiology', name: 'Cardiology & Cardiac Surgery', slug: 'cardiology', icon: '❤️', description: 'Comprehensive heart care including interventional cardiology and bypass surgery.' },
  { id: 'oncology', name: 'Cancer Care', slug: 'oncology', icon: '🩺', description: 'End-to-end cancer treatment with medical, surgical and radiation oncology.' },
  { id: 'neurology', name: 'Neurology & Neurosurgery', slug: 'neurology', icon: '🧠', description: 'Advanced brain and spine care with cutting-edge surgical techniques.' },
  { id: 'orthopaedics', name: 'Orthopaedics', slug: 'orthopaedics', icon: '🦴', description: 'Joint replacement, sports injuries and complex bone surgeries.' },
  { id: 'nephrology', name: 'Nephrology & Transplant', slug: 'nephrology', icon: '🫀', description: 'Kidney disease management, dialysis and organ transplantation.' },
  { id: 'gastroenterology', name: 'Gastroenterology', slug: 'gastroenterology', icon: '🔬', description: 'Complete digestive system care including liver and pancreas.' },
  { id: 'paediatrics', name: 'Paediatrics & Neonatology', slug: 'paediatrics', icon: '👶', description: 'Specialised care for newborns, children and adolescents.' },
  { id: 'gynaecology', name: 'Obstetrics & Gynaecology', slug: 'gynaecology', icon: '🌸', description: 'Maternity care, fertility and women\'s health services.' },
  { id: 'ophthalmology', name: 'Ophthalmology', slug: 'ophthalmology', icon: '👁️', description: 'Comprehensive eye care from cataract surgery to retinal conditions.' },
  { id: 'urology', name: 'Urology', slug: 'urology', icon: '🫁', description: 'Urinary tract and male reproductive system care.' },
  { id: 'pulmonology', name: 'Pulmonology', slug: 'pulmonology', icon: '💨', description: 'Respiratory medicine including asthma, COPD and lung cancer.' },
  { id: 'rheumatology', name: 'Rheumatology', slug: 'rheumatology', icon: '🦱', description: 'Autoimmune and inflammatory joint disease management.' },
  { id: 'dermatology', name: 'Dermatology', slug: 'dermatology', icon: '✨', description: 'Medical and cosmetic skin care by expert dermatologists.' },
  { id: 'endocrinology', name: 'Endocrinology', slug: 'endocrinology', icon: '⚗️', description: 'Diabetes, thyroid and hormonal disorder management.' },
  { id: 'haematology', name: 'Haematology', slug: 'haematology', icon: '🩸', description: 'Blood disorders, bone marrow transplant and haemato-oncology.' },
  { id: 'transplant', name: 'Organ Transplant', slug: 'organ-transplant', icon: '🫶', description: 'Kidney, liver, heart and bone marrow transplantation.' },
  { id: 'plastic-surgery', name: 'Plastic & Reconstructive Surgery', slug: 'plastic-surgery', icon: '🌟', description: 'Reconstructive and aesthetic procedures by expert surgeons.' },
  { id: 'radiology', name: 'Radiology & Imaging', slug: 'radiology', icon: '📡', description: 'State-of-the-art diagnostic imaging including MRI, CT and PET scans.' },
  { id: 'anaesthesia', name: 'Anaesthesiology & Critical Care', slug: 'anaesthesiology', icon: '💉', description: 'Safe anaesthesia and intensive care for critical patients.' },
  { id: 'emergency', name: 'Emergency Medicine', slug: 'emergency', icon: '🚨', description: '24×7 emergency services with rapid response teams.' },
];

export const featuredSpecialities = specialities.slice(0, 10);

export const hospitals = [
  {
    id: 'mazumdar-shaw-bangalore',
    name: 'Mazumdar Shaw Medical Centre',
    city: 'Bengaluru',
    state: 'Karnataka',
    slug: 'mazumdar-shaw-bangalore',
    beds: 1400,
    specialities: ['Cancer Care', 'Cardiology', 'Neurology'],
    accreditations: ['JCI', 'NABH'],
    phone: '080-71222222',
    image: '/hospitals/bangalore.jpg',
    description: 'India\'s largest cancer hospital and a premier multi-speciality quaternary care centre.',
    established: 2009,
  },
  {
    id: 'narayana-health-city',
    name: 'Narayana Health City',
    city: 'Bengaluru',
    state: 'Karnataka',
    slug: 'health-city-bangalore',
    beds: 3000,
    specialities: ['Cardiac Surgery', 'Organ Transplant', 'Paediatrics'],
    accreditations: ['JCI', 'NABH'],
    phone: '080-71222222',
    image: '/hospitals/health-city.jpg',
    description: 'World\'s largest cardiac care hospital. Over 6,000 open heart surgeries annually.',
    established: 2001,
  },
  {
    id: 'dhruva-delhi',
    name: 'Narayana Superspeciality Hospital',
    city: 'Gurugram',
    state: 'Haryana',
    slug: 'narayana-gurugram',
    beds: 250,
    specialities: ['Cardiology', 'Orthopaedics', 'Gastroenterology'],
    accreditations: ['NABH'],
    phone: '0124-4511600',
    image: '/hospitals/gurugram.jpg',
    description: 'Premium superspeciality hospital serving Delhi NCR with cutting-edge care.',
    established: 2015,
  },
  {
    id: 'rubnagar-kolkata',
    name: 'Narayana Multispeciality Hospital',
    city: 'Kolkata',
    state: 'West Bengal',
    slug: 'narayana-kolkata',
    beds: 625,
    specialities: ['Oncology', 'Nephrology', 'Cardiology'],
    accreditations: ['NABH'],
    phone: '033-30023000',
    image: '/hospitals/kolkata.jpg',
    description: 'Eastern India\'s foremost multispeciality hospital with 40+ specialities.',
    established: 2012,
  },
  {
    id: 'jamshedpur',
    name: 'Brahmananda Narayana Hospital',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    slug: 'narayana-jamshedpur',
    beds: 350,
    specialities: ['Cardiac Care', 'Neurology', 'Orthopaedics'],
    accreditations: ['NABH'],
    phone: '0657-6630000',
    image: '/hospitals/jamshedpur.jpg',
    description: 'Comprehensive superspeciality care for Jharkhand and surrounding regions.',
    established: 2008,
  },
  {
    id: 'cayman',
    name: 'Narayana Health City — Cayman Islands',
    city: 'Grand Cayman',
    state: 'Cayman Islands',
    slug: 'cayman-islands',
    beds: 104,
    specialities: ['Cardiac Surgery', 'Orthopaedics', 'Oncology'],
    accreditations: ['JCI'],
    phone: '+1-345-945-7300',
    image: '/hospitals/cayman.jpg',
    description: 'World-class healthcare in the Caribbean. Serving Americas and international patients.',
    established: 2014,
  },
];

export const doctors = [
  {
    id: 1,
    name: 'Dr. Devi Prasad Shetty',
    designation: 'Chairman & Founder',
    speciality: 'Cardiac Surgery',
    hospital: 'Health City, Bengaluru',
    experience: '40+ years',
    available: true,
    languages: ['English', 'Kannada', 'Hindi'],
    image: '/images/doctors/dr-shetty.jpg',
    rating: 5.0,
    reviews: 12400,
    slug: 'devi-prasad-shetty',
  },
  {
    id: 2,
    name: 'Dr. Sreekanth Shetty',
    designation: 'Chief of Oncology',
    speciality: 'Surgical Oncology',
    hospital: 'Mazumdar Shaw, Bengaluru',
    experience: '25+ years',
    available: true,
    languages: ['English', 'Kannada'],
    image: '/images/doctors/dr-sreekanth.jpg',
    rating: 4.9,
    reviews: 3200,
    slug: 'sreekanth-shetty',
  },
  {
    id: 3,
    name: 'Dr. Ashwin Sunil Porwal',
    designation: 'Senior Consultant',
    speciality: 'Neurosurgery',
    hospital: 'Narayana Hospital, Gurugram',
    experience: '18+ years',
    available: false,
    languages: ['English', 'Hindi'],
    image: '/images/doctors/dr-ashwin.jpg',
    rating: 4.8,
    reviews: 1840,
    slug: 'ashwin-sunil-porwal',
  },
  {
    id: 4,
    name: 'Dr. Priya Nair',
    designation: 'Consultant Cardiologist',
    speciality: 'Cardiology',
    hospital: 'Narayana Hospital, Kolkata',
    experience: '15+ years',
    available: true,
    languages: ['English', 'Bengali', 'Hindi'],
    image: '/images/doctors/dr-priya.jpg',
    rating: 4.8,
    reviews: 2100,
    slug: 'priya-nair',
  },
  {
    id: 5,
    name: 'Dr. Rajiv Mahajan',
    designation: 'HOD — Orthopaedics',
    speciality: 'Joint Replacement',
    hospital: 'Health City, Bengaluru',
    experience: '22+ years',
    available: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    image: '/images/doctors/dr-rajiv.jpg',
    rating: 4.9,
    reviews: 2780,
    slug: 'rajiv-mahajan',
  },
  {
    id: 6,
    name: 'Dr. Sunitha Reddy',
    designation: 'Senior Gynaecologist',
    speciality: 'Obstetrics & Gynaecology',
    hospital: 'Mazumdar Shaw, Bengaluru',
    experience: '20+ years',
    available: true,
    languages: ['English', 'Telugu', 'Kannada'],
    image: '/images/doctors/dr-sunitha.jpg',
    rating: 4.7,
    reviews: 1950,
    slug: 'sunitha-reddy',
  },
];

export const healthPackages = [
  {
    id: 1,
    name: 'Comprehensive Health (above 45 years)',
    tests: 68,
    price: 2999,
    originalPrice: 5500,
    popular: true,
    includes: ['CBC', 'Lipid Profile', 'Blood Sugar', 'Thyroid', 'Chest X-Ray', 'ECG', 'Doctor Consultation'],
  },
  {
    id: 2,
    name: 'Prime Health (35-45 years)',
    tests: 92,
    price: 4999,
    originalPrice: 8500,
    popular: false,
    includes: ['All Comprehensive Tests', 'Ultrasound Abdomen', 'Stress Test', 'Pulmonology', 'Ophthalmology'],
  },
  {
    id: 3,
    name: 'Vital Care (below 35 years)',
    tests: 28,
    price: 2499,
    originalPrice: 4200,
    popular: false,
    includes: ['Echo', 'ECG', 'Stress Test', 'Lipid Profile', 'Troponin', 'Cardiologist Consult'],
  },
  {
    id: 4,
    name: 'Prime Health (40-45 years)',
    tests: 55,
    price: 2799,
    originalPrice: 4800,
    popular: true,
    includes: ['Pap Smear', 'Mammography', 'Bone Density', 'Hormonal Panel', 'Gynaecologist Consult'],
  },
  {
    id: 5,
    name: 'Enhanced Health (above 45 years)',
    tests: 78,
    price: 3499,
    originalPrice: 6200,
    popular: false,
    includes: ['All Comprehensive Tests', 'PSA (Men)', 'CA-125 (Women)', 'Cardiac Risk Profile', 'Geriatrician Consult'],
  },
];

export const healthArticles = [
  {
    id: 1,
    title: 'Understanding Heart Failure: Symptoms, Causes and Treatment',
    category: 'Cardiology',
    snippet: 'Heart failure doesn\'t mean the heart has stopped working. Learn about the early warning signs and modern treatment options available at Narayana Health.',
    date: '2026-05-12',
    readTime: '6 min',
    slug: 'understanding-heart-failure',
    image: '/images/articles/heart.jpg',
  },
  {
    id: 2,
    title: 'Early Detection of Cancer: Why Screening Matters',
    category: 'Oncology',
    snippet: 'Regular cancer screening can detect cancer before symptoms appear, significantly improving treatment outcomes and survival rates.',
    date: '2026-05-08',
    readTime: '8 min',
    slug: 'cancer-early-detection',
    image: '/images/articles/cancer.jpg',
  },
  {
    id: 3,
    title: 'Knee Replacement Surgery: What to Expect',
    category: 'Orthopaedics',
    snippet: 'Modern knee replacement is a highly successful procedure. Here\'s everything you need to know before, during and after surgery.',
    date: '2026-04-28',
    readTime: '10 min',
    slug: 'knee-replacement-guide',
    image: '/images/articles/knee.jpg',
  },
  {
    id: 4,
    title: 'Managing Type 2 Diabetes with Diet and Lifestyle',
    category: 'Endocrinology',
    snippet: 'Practical, evidence-based strategies to manage blood sugar levels through nutrition, exercise and medication when needed.',
    date: '2026-04-20',
    readTime: '7 min',
    slug: 'managing-type-2-diabetes',
    image: '/images/articles/diabetes.jpg',
  },
];

export const trustStats = [
  { value: '2.5M+', label: 'Patients Treated', suffix: '' },
  { value: '64K+', label: 'International Patients', suffix: '' },
  { value: '78', label: 'Nationalities Served', suffix: '' },
  { value: '30+', label: 'Medical Specialities', suffix: '' },
];

export const cities = [
  'Bengaluru', 'Delhi', 'Gurugram', 'Kolkata', 'Mumbai',
  'Mysuru', 'Jaipur', 'Ahmedabad', 'Jamshedpur', 'Raipur',
  'Jammu', 'Guwahati', 'Dharwad', 'Kolar', 'Cayman Islands'
];
